In [1]:
import numpy as np

In [2]:
points=np.random.randn(10,4)

In [5]:
points.shape[1]

4

In [7]:
def get_lst_dict(points,no_of_hyperplanes):
    dim=points.shape[1]
    hyperplanes=np.random.normal(size=(no_of_hyperplanes,dim))
    lsh_dict={}
    for i in range(points.shape[0]):
        point=points[i]
        key=[]
        for j in range(no_of_hyperplanes):
            wTx=np.dot(hyperplanes[j],point)
            if wTx>=0:
                key.append(1)
            else:
                key.append(-1)
        key=tuple(key)
        if key not in lsh_dict:
            lsh_dict[key]=[]
        lsh_dict[key].append(point)
    return lsh_dict
  

In [8]:
points=np.random.randn(10,3)
no_of_hyperplanes=3
lsh_dict=get_lst_dict(points,no_of_hyperplanes)

In [9]:
lsh_dict

{(1, -1, 1): [array([-0.78766286, -1.08436449, -0.10752544])],
 (-1, -1, -1): [array([ 0.95781025,  0.72924268, -1.62177371])],
 (1, 1, -1): [array([0.7940076 , 0.63847709, 0.40640927])],
 (-1, 1, -1): [array([ 0.73231536,  0.86641158, -0.71081368]),
  array([ 1.64080092,  2.05659241, -0.18052318])],
 (-1, 1, 1): [array([-1.07134289,  1.31352856,  0.18069411]),
  array([-0.64066167, -0.26368253, -0.43440842])],
 (1, 1, 1): [array([-0.10604922,  1.91707806,  1.99409485]),
  array([0.42062363, 0.83456877, 0.51557932]),
  array([-1.02349955, -0.55828439,  1.04875323])]}