In [1]:
import numpy as np

In [2]:
a1=np.arange(9).reshape(3,3)
a2=np.arange(1).reshape(1,1)

In [3]:
a1+a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
a3=np.arange(9).reshape(3,3)
a4=np.arange(9).reshape(3,3)

In [5]:
a3+a4

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [6]:
a5=np.arange(9).reshape(3,3)
a6=np.arange(3).reshape(1,3)

In [7]:
a5+a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [8]:
a7=np.arange(9).reshape(3,3)
a8=np.arange(3).reshape(3,1)

In [9]:
a7+a8

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [10]:
a9=np.arange(9).reshape(3,3)
a10=np.arange(2).reshape(1,2)

In [11]:
a9+a10

ValueError: operands could not be broadcast together with shapes (3,3) (1,2) 

In [12]:
a11=np.arange(9).reshape(3,3)
a12=np.arange(6).reshape(1,6)

In [13]:
a11+a12

ValueError: operands could not be broadcast together with shapes (3,3) (1,6) 

In [14]:
a13=np.arange(9).reshape(1,3,3)
a14=np.arange(3).reshape(1,3)

In [15]:
a13+a14

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]]])

In [16]:
a15=np.arange(9).reshape(3,3)
a16=np.arange(3).reshape(3,1)

In [17]:
a15+a16

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [18]:
a17=np.arange(12).reshape(4,3)
a18=np.arange(4).reshape(1,4)

In [19]:
a17+a18

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [20]:
arr1=np.array([23,12,45,15,7,90,8,88,9])

In [21]:
normalized_array=arr1/np.max(arr1)

In [22]:
normalized_array

array([0.25555556, 0.13333333, 0.5       , 0.16666667, 0.07777778,
       1.        , 0.08888889, 0.97777778, 0.1       ])

In [23]:
arr2=np.array([23,12,45,15,7,90,8,88,9])

In [24]:
meu=np.mean(arr2)

In [25]:
sd=np.std(arr2)

In [26]:
std_array=(arr2-meu)/sd

In [27]:
std_array

array([-0.31345378, -0.65825295,  0.37614454, -0.56421681, -0.81497984,
        1.78668657, -0.78363446,  1.72399582, -0.75228908])

In [29]:
np.mean(std_array)

np.float64(1.2335811384723961e-17)

In [30]:
np.std(std_array)

np.float64(1.0)

In [31]:
aa=np.arange(9).reshape(3,3)

In [32]:
np.vstack(aa)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.hstack(aa)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
aa1=np.array([3,4,5,6,7,8,99])

In [35]:
np.vstack(aa1)

array([[ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [99]])

In [36]:
np.hstack(aa1)

array([ 3,  4,  5,  6,  7,  8, 99])

In [38]:
aaa1=np.arange(9).reshape(1,3,3)
aaa2=np.arange(9).reshape(1,3,3)

In [39]:
aaa1*aaa2

array([[[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]]])

In [40]:
aa4=np.arange(9).reshape(3,3)

In [41]:
np.linalg.inv(aa4)

LinAlgError: Singular matrix

In [42]:
np.linalg.det(aa4)

np.float64(0.0)

In [43]:
m1=np.array([[2,3],[1,5]])

In [44]:
np.linalg.inv(m1)

array([[ 0.71428571, -0.42857143],
       [-0.14285714,  0.28571429]])

In [45]:
m2=np.array([[1,2,3],[4,0,9]])

In [46]:
np.linalg.inv(m2)

LinAlgError: Last 2 dimensions of the array must be square

In [48]:
np.linalg.matrix_rank(aa4)

np.int64(2)

In [49]:
aa4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
np.linalg.trace(aa4)

np.int64(12)

In [52]:
np.linalg.matrix_transpose(aa4)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])