In [1]:
import numpy as np

In [2]:
aa1=np.array([2,3,4,5,6,7,8])

In [3]:
aa2=aa1.copy()

In [4]:
aa1[1]=1000

In [5]:
aa1

array([   2, 1000,    4,    5,    6,    7,    8])

In [6]:
aa2

array([2, 3, 4, 5, 6, 7, 8])

In [7]:
np.shares_memory(aa1,aa2)

False

In [8]:
aa3=np.array([12,13,24,67,88])

In [9]:
aa4=aa3.view()

In [10]:
aa3[1]=1000

In [11]:
aa3

array([  12, 1000,   24,   67,   88])

In [12]:
aa4

array([  12, 1000,   24,   67,   88])

In [13]:
np.shares_memory(aa3,aa4)

True

In [14]:
aa6=np.array([4,5,6,7,8,9])

In [15]:
aa7=aa6[2:]

In [16]:
np.shares_memory(aa6,aa7)

True

In [17]:
aa8=aa6+1

In [18]:
aa6

array([4, 5, 6, 7, 8, 9])

In [19]:
aa8

array([ 5,  6,  7,  8,  9, 10])

In [20]:
np.shares_memory(aa6,aa8)

False

In [21]:
aa9=np.array([2,3,4,5,6,7])

In [22]:
aa10=aa9[2:]=1000

In [23]:
aa9

array([   2,    3, 1000, 1000, 1000, 1000])

In [24]:
aa10

1000

In [25]:
np.shares_memory(aa9,aa10)

False

In [26]:
aa11=np.array([2,3,45,67,89,0])

In [27]:
a12=aa11**2

In [30]:
np.shares_memory(aa11,a12)

False

In [31]:
aa11

array([ 2,  3, 45, 67, 89,  0])

In [35]:
a13=np.array([0,0,0,0,0,0])

In [36]:
a13=aa11[::-1]

In [37]:
np.shares_memory(aa11,a13)

True

In [38]:
a13=np.array([0,0,0,0,0,0,0,0,0])

In [39]:
a13[3:]=aa11[: :-1]

In [40]:
a13

array([ 0,  0,  0,  0, 89, 67, 45,  3,  2])

In [41]:
aa11

array([ 2,  3, 45, 67, 89,  0])

In [42]:
np.shares_memory(aa11,a13)

False

In [43]:
arr1=np.array([12,"mayur",56.7])

In [44]:
arr1

array(['12', 'mayur', '56.7'], dtype='<U32')

In [45]:
lst=[12,"mayur",23.5]

In [46]:
lst

[12, 'mayur', 23.5]

In [47]:
np.max(arr1)

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> None

In [48]:
arr1

array(['12', 'mayur', '56.7'], dtype='<U32')

In [49]:
arr1[1]=1000

In [50]:
arr1

array(['12', '1000', '56.7'], dtype='<U32')

In [51]:
import pandas as pd

In [52]:
df=pd.read_csv("iris.csv")

In [53]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]